name 'learn_chef_marius'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures learn_chef_marius'
long_description 'Installs/Configures learn_chef_marius'
version '0.1.4'
